### ISSUE TITLE
build

### ISSUE THREAD

**Issue by Imagle** [chiwanpark/flume-ng-redis#10]
Hi, I clone this repository and run 'mvn package' on my computer, but there is no .jar file generated.

**Comment by chiwanpark** [comment]
Hello. Doesn't maven fail to build? I think that maven fails to build package. If fail to build, please send maven log into this issue. Otherwise (If not fail to build), please check target directory in project directory.

**Comment by Imagle** [comment]
this is the log:
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.chiwanpark.flume.plugins:flume-ng-redis:jar:0.1
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 61, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building flume-ng-redis 0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.6.3.201306030806:prepare-agent (prepare-agent) @ flume-ng-redis ---
[INFO] argLine set to -javaagent:/Users/lynn/.m2/repository/org/jacoco/org.jacoco.agent/0.6.3.201306030806/org.jacoco.agent-0.6.3.201306030806-runtime.jar=destfile=/Users/lynn/Dev/flume-ng-redis/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ flume-ng-redis ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/lynn/Dev/flume-ng-redis/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ flume-ng-redis ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/lynn/Dev/flume-ng-redis/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ flume-ng-redis ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ flume-ng-redis ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/lynn/Dev/flume-ng-redis/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ flume-ng-redis ---
[INFO] Surefire report directory: /Users/lynn/Dev/flume-ng-redis/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
objc[21477]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_9dd1198.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
	at org.jacoco.agent.rt.internal_9dd1198.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:99)
	at org.jacoco.agent.rt.internal_9dd1198.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_9dd1198.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.lang.Class.getField(Class.java:1695)
	at org.jacoco.agent.rt.internal_9dd1198.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:136)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed
/bin/sh: line 1: 21477 Abort trap: 6           /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/bin/java -javaagent:/Users/lynn/.m2/repository/org/jacoco/org.jacoco.agent/0.6.3.201306030806/org.jacoco.agent-0.6.3.201306030806-runtime.jar=destfile=/Users/lynn/Dev/flume-ng-redis/target/jacoco.exec -jar /Users/lynn/Dev/flume-ng-redis/target/surefire/surefirebooter7202789418110369509.jar /Users/lynn/Dev/flume-ng-redis/target/surefire/surefire2268088692997739475tmp /Users/lynn/Dev/flume-ng-redis/target/surefire/surefire_02961442684640900tmp

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.629 s
[INFO] Finished at: 2015-03-10T22:14:36+08:00
[INFO] Final Memory: 21M/207M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project flume-ng-redis: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by chiwanpark** [comment]
@Imagle Thanks. I will check and answer as soon as possible.

**Comment by Imagle** [comment]
thanks very much

**Comment by chiwanpark** [comment]
@Imagle Hello. I found some solutions to deal with this problem. The reason to build failure is that the jacoco plugin version 0.6.3.201306030806 doesn't support Java 8 compiler. In flume-ng-redis 0.2, the version of jacoco plugin upgraded to 0.7.2.201409121644. I recommend upgrading version of flume-ng-redis to 0.2 or downgrading Java version to 0.7 to you.

**Comment by Imagle** [comment]
Okay，I will have a try. 3ks.

**Comment by chiwanpark** [comment]
@Imagle If you success to build using my solutions, please close this issue. :)

**Comment by Imagle** [comment]
thanks, I successfully build follow you suggestions. But it still have no .jar files under target folder.
~/Dev/flume-ng-redis/target on ⭠ d611307 ⌚ 22:42:51
$ ls
classes                generated-test-sources maven-status           test-classes
generated-sources      jacoco.exec            surefire

**Comment by chiwanpark** [comment]
@Imagle Hmm.. That is strange. Could you upload maven log messages?

**Comment by Imagle** [comment]
log:
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.chiwanpark.flume.plugins:flume-ng-redis:jar:0.2.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 61, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building flume-ng-redis 0.2.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.2.201409121644:prepare-agent (prepare-agent) @ flume-ng-redis ---
[INFO] argLine set to -javaagent:/Users/lynn/.m2/repository/org/jacoco/org.jacoco.agent/0.7.2.201409121644/org.jacoco.agent-0.7.2.201409121644-runtime.jar=destfile=/Users/lynn/Dev/flume-ng-redis/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ flume-ng-redis ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/lynn/Dev/flume-ng-redis/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ flume-ng-redis ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/lynn/Dev/flume-ng-redis/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ flume-ng-redis ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ flume-ng-redis ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/lynn/Dev/flume-ng-redis/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ flume-ng-redis ---
[INFO] Surefire report directory: /Users/lynn/Dev/flume-ng-redis/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
objc[33465]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Running com.chiwanpark.flume.plugins.RedisPublishDrivenSinkTest
main> [2015-03-10 22:54:10] [RedisPublishDrivenSink] [56] [INFO] Flume Redis Publish Sink Configured 
main> [2015-03-10 22:54:10] [RedisPublishDrivenSink] [69] [INFO] Redis Connected. (host: localhost, port: 6379, timeout: 2000) 
main> [2015-03-10 22:54:10] [MonitoredCounterGroup] [119] [INFO] Monitored counter group for type: CHANNEL, name: null: Successfully registered new MBean. 
main> [2015-03-10 22:54:10] [MonitoredCounterGroup] [95] [INFO] Component type: CHANNEL, name: null started 
Thread-2> [2015-03-10 22:54:11] [RedisPublishDrivenSinkTest] [83] [INFO] Jedis is disconnected. 
main> [2015-03-10 22:54:12] [RedisPublishDrivenSinkTest] [103] [INFO] Test Publish feature in RedisPublishDrivenSink 
main> [2015-03-10 22:54:12] [RedisPublishDrivenSinkTest] [111] [INFO] Put test message into channel 
main> [2015-03-10 22:54:12] [RedisPublishDrivenSinkTest] [118] [INFO] Transaction is closed

**Comment by chiwanpark** [comment]
@Imagle Oh. Are they full log messages? If then, the build doesn't succeed. I think that you are building without redis server in build machine. You should skip tests to build without redis server. Could you build package with `mvn package -DskipTests` command?

**Comment by Imagle** [comment]
Yes, you are right, I run 'mvn-package' command without redis-server on my machine. 
I will use `mvn package -DskipTests` instead.

**Comment by Imagle** [comment]
Thanks very much.
If succeed, I will close this issue.

**Comment by Imagle** [comment]
Thanks very much. 
Build successfully under you instruction.

**Comment by chiwanpark** [comment]
Okay. I'll add this contents into README.md. Thanks for your question.
