### ISSUE TITLE
Handle event body as binary instead of UTF-8

### ISSUE THREAD

**Issue by philipphoffmann** [chiwanpark/flume-ng-redis#19]
First off, thx for providing the plugin, great job.

We have a slight issue with it though. Using the `RawMessageHandler` we found that the plugin always parses the incoming flume events binary body as UTF-8 and also sends the body along as UTF-8. This breaks bodies which rely on the binary encoding. In our case we have binary thrift in the event body, which when interpreted as UTF-8 and put into Redis as UTF-8 changed the binary encoding.

We got this fixed for us by modifying the plugin a bit. Before opening a pull request, I would like to know if this change actually makes sense to you. In that case, I'm happy to share our changes.

**Comment by chiwanpark** [comment]
Hi @philipphoffmann, sorry for late response. I'd welcome to any pull requests! Please open a pull request your changes.

**Comment by philipphoffmann** [comment]
Alright then, I will put together a pull request ...
